name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu-x64:
    runs-on: ubuntu-latest
    name: Build & Test (Ubuntu x64)
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -r linux-x64

      - name: Test
        run: dotnet test --no-build --verbosity normal

  build-ubuntu-x86:
    runs-on: ubuntu-latest
    name: Build & Test (Ubuntu x86)
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -r linux-x86

      - name: Test
        run: dotnet test --no-build --verbosity normal

  build-windows-x64:
    runs-on: windows-latest
    name: Build & Test (Windows x64)
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -r win-x64

      - name: Test
        run: dotnet test --no-build --verbosity normal

  build-windows-x86:
    runs-on: windows-latest
    name: Build & Test (Windows x86)
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -r win-x86

      - name: Test
        run: dotnet test --no-build --verbosity normal

  build-macos-x64:
    runs-on: macos-latest
    name: Build & Test (macOS x64)
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -r osx-x64

      - name: Test
        run: dotnet test --no-build --verbosity normal
